### PR TITLE
chore(tests): migrate to Jest 

### PR DESCRIPTION
**Pull request by aaronmcadam**
### TODO

- [ ] Replace mocha with jest
- [x] Move Jest configuration to an `rc` file
- [x] Try using node resolver: `"snapshotSerializers": ["enzyme-to-json/serializer"]`.
- [x] Remove `yarn.lock` files
- [x] Remove testing on storyshots repo. 
- [ ] Replace usage of `chai` and `sinon` with Jest and Enzyme. 
- [ ] Use `foo.mockImplementation(() => {})` or similar, for complex mocks
- [ ] Remove test util dependencies from packages
- [ ] Centralise testing of packages from root

### CODE REVIEW

**Comment by aaronmcadam** [comment]
@ndelangen Do we want to fix the "ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning" console warnings in this branch?

**Comment by ndelangen** [comment]
All the repo's are in, so I can help get this merged if you want?

I'd like this repo to provide a clear way of unittesting everything in the monorepo. 0 warnings, 0 errors.
But:
> Don't let perfect be the enemy of great

**Comment by aaronmcadam** [comment]
@ndelangen I've been looking into removing the console warnings on my projects today. We'll have to wait for `enzyme` to release a new version, which includes [this PR](https://github.com/airbnb/enzyme/pull/876) that fixes the issues.

Those fixes should be part of a greater React 15.5 upgrade (including migrating to the `prop-types` package, which I've done today on my own work and it went OK)

I agree that we should get this merged ASAP. What are the main things we want to achieve with this? I'd like to get rid of all the `sinon` and `chai` usage if we can.

**Comment by ndelangen** [comment]
I updated the todo-list in the OP

**Comment by ndelangen** [comment]
Closed in favour of https://github.com/storybooks/storybook/pull/771

**Pull request closed without merging**
